name: cinemalist
description: TheMovieDB API Build with Flutter

publish_to: 'none' 

version: 1.4.2+106

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  equatable: 2.0.4
  http: 0.13.5
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  shimmer: 2.0.0
  carousel_slider: 4.1.1
  intl: 0.17.0
  google_fonts: 3.0.1
  cached_network_image: 3.2.1
  url_launcher: 6.1.5
  youtube_player_flutter: 8.1.0
  logger: ^1.1.0
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.11
  connectivity_plus: ^2.3.6+1
  share_plus: ^4.0.10+1
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_launcher_icons: 0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/tmdb/
